# Generated by Django 3.2 on 2022-01-10 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_available',
            field=models.BooleanField(default=False, verbose_name='موجود'),
        ),
    ]
